### ISSUE TITLE
Can you provide the download address of all 2958 evaluation data sets in mpii_dataset.t7?

### ISSUE THREAD

**Issue by TeslaHua** [1adrianb/binary-human-pose-estimation#15]
Hi, adrianb,
      When I run your evaluation code (mode==eval), the getFileList() function in utils.lua extracts 2958 data. But download-content.lua only provides ten images running demo code (mode==demo). Can you provide all 2958 image data to me? thank you very much.

**Comment by 1adrianb** [comment]
Hi @TeslaHua,

The dataset can be download from http://human-pose.mpi-inf.mpg.de/ The ids are the ones used in: Joint Training of a Convolutional Network and a Graphical Model for Human Pose Estimation, Tompson et al, 2014
