### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by ktak199** [1adrianb/binary-human-pose-estimation#2]
I got the message below.
Environment: Ubuntu14.04, CUDA7.0, cudnn4.0
Could anyone help me?
Thank you in advance.

`$ th main.lua`  
`~/torch/install/bin/luajit: ~/torch/install/share/lua/5.1/nn/Container.lua:67:`  
`In 11 module of nn.Sequential:`  
`~/torch/install/share/lua/5.1/cudnn/BatchNormalization.lua:69: bad argument #1 to 'resizeAs'`   `(torch.CudaTensor expected, got userdata)`  
`stack traceback:`  
`	[C]: in function 'resizeAs'`  
`	...torch/install/share/lua/5.1/cudnn/BatchNormalization.lua:69: in function`   `<...torch/install/share/lua/5.1/cudnn/BatchNormalization.lua:63>`  
`	[C]: in function 'xpcall'`  
`	~/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'`  
`	~/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'`  
`	~/torch/install/share/lua/5.1/optnet/init.lua:387: in function 'optimizeMemory'`  
`	main.lua:27: in main chunk`  
`	[C]: in function 'dofile'`  
`	~/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk`  
`	[C]: at 0x00406670`  
`WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.`  
`stack traceback:`  
`	[C]: in function 'error'`  
`	~/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'`  
`	~/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'`  
`	~/torch/install/share/lua/5.1/optnet/init.lua:387: in function 'optimizeMemory'`  
`	main.lua:27: in main chunk`  
`	[C]: in function 'dofile'`  
`	~/torch/install/lib/luarocks`

**Comment by 1adrianb** [comment]
@ktak199 It looks to me that the batchnorm layer changed a bit from cudnn4 to 5 and ``self.running_std`` doesn't exist anymore. You can either upgrade to cudnn5 or if this is not an option you can convert the ``cudnn.SpatialBatchNormalisation`` layer to it's nn counterpart. Something like this:

```
cudnn.convert(model, nn, function(module)
   return torch.type(module):find('SpatialBatchNormalisation')
end)
```

**Comment by ktak199** [comment]
@1adrianb I upgraded to cuda8.0 & cudnn5.1. It worked. Thank you.
