### ISSUE TITLE
Prediction for a New image

### ISSUE THREAD

**Issue by ktak199** [1adrianb/binary-human-pose-estimation#3]
How to get the prediction for a new image?
I renamed dataset/mpii/images/07218876.jpg dataset/mpii/images/07218876(copy).jpg
and created a new dataset/mpii/images/07218876.jpg file.
Then I got the prediction for the old dataset/mpii/images/07218871.jpg.
Thank you in advance.

**Comment by 1adrianb** [comment]
The demo/evaluation procedure fallows the MPII dataset protocol (please check the original [page](http://human-pose.mpi-inf.mpg.de/#evaluation), which require a point (usually located on torso) and an aproximative scale for each person in the image. 

You can change the images and provide the corresponding points and scales by tweaking the ``function utils.getFileList(opts)`` located in ``utils.lua``
