### ISSUE TITLE
error when exec th download-content.lua

### ISSUE THREAD

**Issue by HaoLiuHust** [1adrianb/binary-human-pose-estimation#5]
liuhao@umaster:~/binary-human-pose-estimation$ th download-content.lua 
/home/liuhao/torch/install/bin/luajit: /home/liuhao/torch/install/share/lua/5.1/trepl/init.lua:389: module 'cURL' not found:No LuaRocks module found for cURL
	no field package.preload['cURL']
	no file '/home/liuhao/.luarocks/share/lua/5.1/cURL.lua'
	no file '/home/liuhao/.luarocks/share/lua/5.1/cURL/init.lua'
	no file '/home/liuhao/torch/install/share/lua/5.1/cURL.lua'
	no file '/home/liuhao/torch/install/share/lua/5.1/cURL/init.lua'
	no file './cURL.lua'
	no file '/home/liuhao/torch/install/share/luajit-2.1.0-beta1/cURL.lua'
	no file '/usr/local/share/lua/5.1/cURL.lua'
	no file '/usr/local/share/lua/5.1/cURL/init.lua'
	no file '/home/liuhao/.luarocks/lib/lua/5.1/cURL.so'
	no file '/home/liuhao/torch/install/lib/lua/5.1/cURL.so'
	no file '/home/liuhao/torch/install/lib/cURL.so'
	no file './cURL.so'
	no file '/usr/local/lib/lua/5.1/cURL.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/liuhao/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	download-content.lua:1: in main chunk
	[C]: in function 'dofile'
	...uhao/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

seems the problem is cURL, but I have installed it, have you encounter this? I am the new guy to torch

**Comment by HaoLiuHust** [comment]
Problem solved with this:
sudo apt-get install libcurl4-openssl-dev
luarocks install Lua-cURL

**Comment by 1adrianb** [comment]
Hi @HaoLiuHust that package (Lua-cURL) is already listed in the requirments and a link is provided to it's home location where you can see if there are othere dependecies. Please check them carefully next time. Thanks.
