### ISSUE TITLE
file can not be downloaded, the project page can not be open

### ISSUE THREAD

**Issue by HaoLiuHust** [1adrianb/binary-human-pose-estimation#6]
when exec th download-content.lua, the image can not be downloaded, and it can not be opened by web browser too

**Comment by 1adrianb** [comment]
Hi @HaoLiuHust I have checked the links and they are fine and there is no downtime reported in the last 24hours. Please try again and check if the connection issues is not at your end. If you still have issues I will try to provide an alternative link.

**Comment by HaoLiuHust** [comment]
Thanks for your warmly reply, could you provide me an alternative link?
