### ISSUE TITLE
Seeking performance benchmarks

### ISSUE THREAD

**Issue by ajhool** [1adrianb/binary-human-pose-estimation#7]
Hi, are there performance benchmarks available for different operating systems? Duration, memory consumption, etc.? 

Would be greatly appreciated, thanks!

**Comment by 1adrianb** [comment]
Hi @ajhool 
The current implementation available is just a prof-of-concept and will not reflect the achievable performance. Our method is build upon the binarization strategy described in the XNOR paper from ECCV 2016 by Rastegari et al and any performance analysis done in their work should also apply to ours. 
All been said we expect that our method can achieve real-time or close to real-time performance on a modern CPU given an optimal implementation.
In addition to your question, the performance should be largely independent of the operating system used.
