### ISSUE TITLE
How to train the module

### ISSUE THREAD

**Issue by Crazod** [1adrianb/binary-human-pose-estimation#8]
Hey @1adrianb , could you give me a guide how can i train the model with my own dataset? Is there an example to train it ?

**Comment by 1adrianb** [comment]
Hi @Crazod , sorry for delay. For an example please reffer to this code for now: https://github.com/allenai/XNOR-Net
I will try to release the training code ASAP. Let me know if you have other questions.

**Comment by Crazod** [comment]
It is a really useful suggestion. I have learn the code in https://github.com/allenai/XNOR-Net and code in bnnspatialconvolution.cu. In the XNOR-net work. There is only code to verification the paper and train the real value model. I want to know how do you to train the binary value model.? I have 2 ideas: 1. train the real value model like XNOR net and finally convert it to binary model. 2. Complete the backward in BinarySpatialConvolution.cu. and train the binary model. But it seems need to store some  intermediate result like weight.  Can you tell me more details?
