### ISSUE TITLE
Training script

### ISSUE THREAD

**Issue by stanciuflorina** [1adrianb/binary-human-pose-estimation#9]
Is there a chance to release a training script in the near future?

**Comment by 1adrianb** [comment]
Hi Florina, unfortunately I have no exact ETA for this. You can probably adapt this code https://github.com/allenai/XNOR-Net and retrain the proposed model in the meantime.

**Comment by stanciuflorina** [comment]
thank you, i will try it out :)

**Comment by stanciuflorina** [comment]
thank you for the suggestion again, i have some problems with the retraining process, maybe you can help. So i tried to adapt the code  https://github.com/allenai/XNOR-Net for this network but when i run the comand for the retraining i get this error: /home/fstanciu/torch/install/share/lua/5.1/trepl/init.lua:389: /home/fstanciu/torch/install/share/lua/5.1/trepl/init.lua:389: /home/fstanciu/torch/install/share/lua/5.1/torch/init.lua:102: while creating metatable bnn.Binary: bad argument #1 (bnn is an invalid module name)
stack traceback:
	[C]: in function 'error'
	/home/fstanciu/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	main.lua:17: in main chunk
	[C]: in function 'dofile'
	...nciu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
it says that i don't have the bnn class but when i listed the luarocks it is there: 
Installed rocks:
----------------

argcheck
   scm-1 (installed) - /home/fstanciu/torch/install/lib/luarocks/rocks

bnn
   1.0-0 (installed) - /home/fstanciu/torch/install/lib/luarocks/rocks

**Comment by 1adrianb** [comment]
@stanciuflorina the missing layer can be found here: https://github.com/1adrianb/bnn.torch
However you can also replace bnn.Binary with BinActiveZ found in the xnor repository.
